### ISSUE TITLE
Tensorflow gpu not working in prod

### ISSUE THREAD

**Issue by starrett67** [3Blades/notebook-servers#64] opened 2018-01-05 12:51 UTC
1. Start up a notebook and launch the getting_started_keras_tensorflow document. 
2. Run all cells
3. Notice the error thrown while importing keras

ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

This error usually means nvidia docker is not running correctly or the machine its running on does not have an nvidia gpu.

**Comment by johngriebel** [comment] 2018-01-05 13:07
This has been resolved for now. The cause is an incorrect value for `NVIDIA_DOCKER_HOST`. The ECS host's IP address can change because we currently use spot instances for GPU availability. When that IP address fails we see this issue, among others. It is not yet decided if we will either a.) disable GPU notebooks altogether, or b.) use reserved instances. Closing this issue since any further work will be in other repositories.

**Closed by johngriebel** 2018-01-05 13:07 UTC
Labels: fix
